#include "Ifx_Types.h"
#include "IfxCpu_Irq.h"

#define IRQ_CANRX_CHANNEL           1U
#define ISR_PRIORITY_CAN_ALRT       14U
#define ISR_PRIORITY_CAN_MOER       15u
#define ISR_PRIORITY_CAN_BOFF       16u
#define ISR_PRIORITY_CAN_LOI        17u

IFX_INTERRUPT(ISR_CanAlrt, 0u, ISR_PRIORITY_CAN_ALRT);
IFX_INTERRUPT(ISR_CanRx, 0u, IRQ_CANRX_CHANNEL);
IFX_INTERRUPT(ISR_CanMoer, 0u, ISR_PRIORITY_CAN_ALRT);
IFX_INTERRUPT(ISR_CanBoff, 0u, ISR_PRIORITY_CAN_BOFF);
IFX_INTERRUPT(ISR_CanLoi, 0u, ISR_PRIORITY_CAN_LOI);
