################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C++_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
SRC_SRCS := 
C++_DEPS := 
CC_DEPS := 
COMPILED_SRCS := 
CPP_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 
SECONDARY_SIZE := 

# Every subdirectory with source files must be described here
SUBDIRS := \
APP/ColDet \
APP/ComMaster \
APP/DcyHandler \
APP/DiagMaster \
APP/EMotorCtrl \
APP/EPSCtrl \
APP/EncCal \
APP/EnergyMgmt \
APP/Iven \
BSW/Com/Can \
BSW/Com/E2e \
BSW/Diag/Dcm \
BSW/Diag/Dem \
BSW/Io/Ain \
BSW/Io/Dma \
BSW/Io/Eru \
BSW/Io/Gtm \
BSW/Io/Irq \
BSW/Mem/Fls \
BSW/Mem/Nvm \
BSW/Sys/Bsw_Wrapper \
BSW/Sys/Crc \
BSW/Sys/McuSm \
BSW/Sys/Os/FreeRTOS \
BSW/Sys/Os/FreeRTOS/portable/MemMang \
BSW/Sys/Os/FreeRTOS/portable/Tasking/TC3 \
BSW/Sys/Os \
BSW/Sys/Smu \
BSW/Sys/SysMgr \
BSW/Sys/Wdg \
Configurations/Debug \
Configurations \
. \
Libraries/Infra/Platform/Tricore/Compilers \
Libraries/Infra/Ssw/TC37A/Tricore \
Libraries/Service/CpuGeneric/StdIf \
Libraries/Service/CpuGeneric/SysSe/Bsp \
Libraries \
Libraries/iLLD/TC37A/Tricore/Can/Can \
Libraries/iLLD/TC37A/Tricore/Can/Std \
Libraries/iLLD/TC37A/Tricore/Cpu/Irq \
Libraries/iLLD/TC37A/Tricore/Cpu/Std \
Libraries/iLLD/TC37A/Tricore/Cpu/Trap \
Libraries/iLLD/TC37A/Tricore/Dma/Dma \
Libraries/iLLD/TC37A/Tricore/Dma/Std \
Libraries/iLLD/TC37A/Tricore/Dts/Dts \
Libraries/iLLD/TC37A/Tricore/Dts/Std \
Libraries/iLLD/TC37A/Tricore/Evadc/Adc \
Libraries/iLLD/TC37A/Tricore/Evadc/Std \
Libraries/iLLD/TC37A/Tricore/Fce/Crc \
Libraries/iLLD/TC37A/Tricore/Fce/Std \
Libraries/iLLD/TC37A/Tricore/Flash/Std \
Libraries/iLLD/TC37A/Tricore/Gtm/Atom/Pwm \
Libraries/iLLD/TC37A/Tricore/Gtm/Atom/Timer \
Libraries/iLLD/TC37A/Tricore/Gtm/Std \
Libraries/iLLD/TC37A/Tricore/Mtu/Std \
Libraries/iLLD/TC37A/Tricore/Pms/Std \
Libraries/iLLD/TC37A/Tricore/Port/Io \
Libraries/iLLD/TC37A/Tricore/Port/Std \
Libraries/iLLD/TC37A/Tricore/Scu/Std \
Libraries/iLLD/TC37A/Tricore/Smu/Std \
Libraries/iLLD/TC37A/Tricore/Src/Std \
Libraries/iLLD/TC37A/Tricore/Stm/Std \
Libraries/iLLD/TC37A/Tricore/_Impl \
Libraries/iLLD/TC37A/Tricore/_PinMap \

