/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC37XPD
 * - package : LQFP176
 */

/*
 * Instructions on how to build this generated file and the Infineon's iLLD library with the TASKING  VX-toolset
 * for TriCore:
 * 1. Provide appropriate include paths to the compiler (-I option) to locate the iLLD library.
 * 2. Provide macro IFX_CFG_USE_COMPILER_DEFAULT_LINKER to the compiler (-D option) to prevent multiple
 *    definitions of symbol '_START' (in cstart.c and IfxCpu_CStart0.c).
 * 3. Disable compiler option 'Automatic inclusion of .sfr files' (-H option) to prevent macros to be redefined.
 */

#ifndef AURIX_PIN_MAPPINGS_H_
#define AURIX_PIN_MAPPINGS_H_

/* Infineon's iLLD library include files */

#include <Port/Io/IfxPort_Io.h>

#include <_PinMap/IfxPort_PinMap.h>


/* Symbolic names for GPIO ports */

// p00_0
#define IFXCFG_PORT_WUP_PDM                     IfxPort_P00_0
#define IFXCFG_PORT_WUP_PDM_MODE                IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_WUP_PDM_PAD_DRIVER          IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_1
#define IFXCFG_PORT_WUP_DMU                     IfxPort_P00_1
#define IFXCFG_PORT_WUP_DMU_MODE                IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_WUP_DMU_PAD_DRIVER          IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_2
#define IFXCFG_PORT_WUP_CBM                     IfxPort_P00_2
#define IFXCFG_PORT_WUP_CBM_MODE                IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_WUP_CBM_PAD_DRIVER          IfxPort_PadDriver_cmosAutomotiveSpeed4

// p00_3
#define IFXCFG_PORT_TEMPERATURESENSOR           IfxPort_P00_3
#define IFXCFG_PORT_TEMPERATURESENSOR_MODE      IfxPort_Mode_inputPullUp
#define IFXCFG_PORT_TEMPERATURESENSOR_PAD_DRIVER IfxPort_PadDriver_cmosAutomotiveSpeed1

// p20_6
#define IFXCFG_PORT_GPIO1                       IfxPort_P20_6
#define IFXCFG_PORT_GPIO1_MODE                  IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_GPIO1_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed4


/* Generic port I/O configuration */

#define IFXCFG_P00_0_IO_CONFIG                  { &IFXCFG_PORT_WUP_PDM, IFXCFG_PORT_WUP_PDM_MODE, IFXCFG_PORT_WUP_PDM_PAD_DRIVER }
#define IFXCFG_P00_1_IO_CONFIG                  { &IFXCFG_PORT_WUP_DMU, IFXCFG_PORT_WUP_DMU_MODE, IFXCFG_PORT_WUP_DMU_PAD_DRIVER }
#define IFXCFG_P00_2_IO_CONFIG                  { &IFXCFG_PORT_WUP_CBM, IFXCFG_PORT_WUP_CBM_MODE, IFXCFG_PORT_WUP_CBM_PAD_DRIVER }
#define IFXCFG_P00_3_IO_CONFIG                  { &IFXCFG_PORT_TEMPERATURESENSOR, IFXCFG_PORT_TEMPERATURESENSOR_MODE, IFXCFG_PORT_TEMPERATURESENSOR_PAD_DRIVER }
#define IFXCFG_P20_6_IO_CONFIG                  { &IFXCFG_PORT_GPIO1, IFXCFG_PORT_GPIO1_MODE, IFXCFG_PORT_GPIO1_PAD_DRIVER }


/* Generic alternate I/O configuration */

// can0_node0
#define IFXCFG_P20_7_IO_CONFIG                  { &IfxPort_P20_7, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P20_8_IO_CONFIG                  { &IfxPort_P20_8, IfxPort_Mode_outputPushPullAlt5, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// eruin0
#define IFXCFG_P15_4_IO_CONFIG                  { &IfxPort_P15_4, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// eruin4
#define IFXCFG_P33_7_IO_CONFIG                  { &IfxPort_P33_7, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// eruin6
#define IFXCFG_P11_10_IO_CONFIG                 { &IfxPort_P11_10, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }

// tout14
#define IFXCFG_P00_5_IO_CONFIG                  { &IfxPort_P00_5, IfxPort_Mode_outputPushPullAlt1, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// tout15
#define IFXCFG_P00_6_IO_CONFIG                  { &IfxPort_P00_6, IfxPort_Mode_outputPushPullAlt1, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// tout16
#define IFXCFG_P00_7_IO_CONFIG                  { &IfxPort_P00_7, IfxPort_Mode_outputPushPullAlt1, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// tout17
#define IFXCFG_P00_8_IO_CONFIG                  { &IfxPort_P00_8, IfxPort_Mode_outputPushPullAlt1, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// tout18
#define IFXCFG_P00_9_IO_CONFIG                  { &IfxPort_P00_9, IfxPort_Mode_outputPushPullAlt1, IfxPort_PadDriver_cmosAutomotiveSpeed4 }


/* Initialization routines */

extern void gpio_init_pins(void);

extern void can0_node0_init_pins(void);

extern void eruin0_init_pins(void);

extern void eruin4_init_pins(void);

extern void eruin6_init_pins(void);

extern void tout14_init_pins(void);

extern void tout15_init_pins(void);

extern void tout16_init_pins(void);

extern void tout17_init_pins(void);

extern void tout18_init_pins(void);


#endif /* AURIX_PIN_MAPPINGS_H_ */
