/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC37XPD
 * - package : LQFP176
 */

#include "aurix_pin_mappings.h"


/* GPIO pin configuration */

static const IfxPort_Io_ConfigPin gpio_pin_table[] = 
{
    IFXCFG_P00_0_IO_CONFIG,
    IFXCFG_P00_1_IO_CONFIG,
    IFXCFG_P00_3_IO_CONFIG,
    IFXCFG_P20_6_IO_CONFIG
};

static const IfxPort_Io_Config gpio_io_config_table = 
{
    sizeof(gpio_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)gpio_pin_table
};

extern void gpio_init_pins(void)
{
    IfxPort_Io_initModule(&gpio_io_config_table);
}


/* CAN0_NODE0 pin configuration */

static const IfxPort_Io_ConfigPin can0_node0_pin_table[] = 
{
    IFXCFG_P20_7_IO_CONFIG,
    IFXCFG_P20_8_IO_CONFIG
};

static const IfxPort_Io_Config can0_node0_io_config_table = 
{
    sizeof(can0_node0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)can0_node0_pin_table
};

extern void can0_node0_init_pins(void)
{
    IfxPort_Io_initModule(&can0_node0_io_config_table);
}


/* ERUIN0 pin configuration */

static const IfxPort_Io_ConfigPin eruin0_pin_table[] = 
{
    IFXCFG_P15_4_IO_CONFIG
};

static const IfxPort_Io_Config eruin0_io_config_table = 
{
    sizeof(eruin0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)eruin0_pin_table
};

extern void eruin0_init_pins(void)
{
    IfxPort_Io_initModule(&eruin0_io_config_table);
}


/* ERUIN4 pin configuration */

static const IfxPort_Io_ConfigPin eruin4_pin_table[] = 
{
    IFXCFG_P33_7_IO_CONFIG
};

static const IfxPort_Io_Config eruin4_io_config_table = 
{
    sizeof(eruin4_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)eruin4_pin_table
};

extern void eruin4_init_pins(void)
{
    IfxPort_Io_initModule(&eruin4_io_config_table);
}


/* ERUIN6 pin configuration */

static const IfxPort_Io_ConfigPin eruin6_pin_table[] = 
{
    IFXCFG_P11_10_IO_CONFIG
};

static const IfxPort_Io_Config eruin6_io_config_table = 
{
    sizeof(eruin6_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)eruin6_pin_table
};

extern void eruin6_init_pins(void)
{
    IfxPort_Io_initModule(&eruin6_io_config_table);
}


/* TOUT14 pin configuration */

static const IfxPort_Io_ConfigPin tout14_pin_table[] = 
{
    IFXCFG_P00_5_IO_CONFIG
};

static const IfxPort_Io_Config tout14_io_config_table = 
{
    sizeof(tout14_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)tout14_pin_table
};

extern void tout14_init_pins(void)
{
    IfxPort_Io_initModule(&tout14_io_config_table);
}


/* TOUT15 pin configuration */

static const IfxPort_Io_ConfigPin tout15_pin_table[] = 
{
    IFXCFG_P00_6_IO_CONFIG
};

static const IfxPort_Io_Config tout15_io_config_table = 
{
    sizeof(tout15_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)tout15_pin_table
};

extern void tout15_init_pins(void)
{
    IfxPort_Io_initModule(&tout15_io_config_table);
}


/* TOUT16 pin configuration */

static const IfxPort_Io_ConfigPin tout16_pin_table[] = 
{
    IFXCFG_P00_7_IO_CONFIG
};

static const IfxPort_Io_Config tout16_io_config_table = 
{
    sizeof(tout16_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)tout16_pin_table
};

extern void tout16_init_pins(void)
{
    IfxPort_Io_initModule(&tout16_io_config_table);
}


/* TOUT17 pin configuration */

static const IfxPort_Io_ConfigPin tout17_pin_table[] = 
{
    IFXCFG_P00_8_IO_CONFIG
};

static const IfxPort_Io_Config tout17_io_config_table = 
{
    sizeof(tout17_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)tout17_pin_table
};

extern void tout17_init_pins(void)
{
    IfxPort_Io_initModule(&tout17_io_config_table);
}


/* TOUT18 pin configuration */

static const IfxPort_Io_ConfigPin tout18_pin_table[] = 
{
    IFXCFG_P00_9_IO_CONFIG
};

static const IfxPort_Io_Config tout18_io_config_table = 
{
    sizeof(tout18_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)tout18_pin_table
};

extern void tout18_init_pins(void)
{
    IfxPort_Io_initModule(&tout18_io_config_table);
}

