#include "Ifx_Types.h"

extern uint8 EnergyMgmt_CanTx_CommandLoad1;
extern uint8 EnergyMgmt_CanTx_CommandLoad2;
extern uint8 EnergyMgmt_CanTx_CommandLoad3;
extern uint8 EnergyMgmt_CanTx_CommandLoad4;
extern uint8 EnergyMgmt_CanTx_CommandLoad5;
extern uint8 EnergyMgmt_CanTx_CommandLoad6;
extern uint8 EnergyMgmt_CanTx_CommandLoad7;
extern uint8 EnergyMgmt_CanTx_CommandLoad8;
extern uint8 EnergyMgmt_CanRx_LoadStatus1;
extern uint8 EnergyMgmt_CanRx_LoadStatus2;
extern uint8 EnergyMgmt_CanRx_LoadStatus3;
extern uint8 EnergyMgmt_CanRx_LoadStatus4;
extern uint8 EnergyMgmt_CanRx_LoadStatus5;
extern uint8 EnergyMgmt_CanRx_LoadStatus6;
extern uint8 EnergyMgmt_CanRx_LoadStatus7;
extern uint8 EnergyMgmt_CanRx_LoadStatus8;
extern uint8 EnergyMgmt_CanRx_IgnitionStatus;
extern uint8 EnergyMgmt_CanTx_VehicleState;
extern uint8 EnergyMgmt_CanRx_StatusDoorLeft;
extern uint8 EnergyMgmt_CanRx_StatusDoorRight;
extern uint8 EnergyMgmt_CanRx_StatusHc05;
extern uint8 EnergyMgmt_CanRx_VoltageMeasured;
extern uint8 EnergyMgmt_CanRx_CurrentMeasured;
extern uint8 EnergyMgmt_CanRx_CurrentMeasured2;
extern uint8 EnergyMgmt_CanTx_PowerSupplyReducedPerformance;

extern void EnergyMgmt_MainFunction(void);
